In [1]:
import pandas as pd
import numpy as np
import torch
from torch import nn, optim

from transformer.vocabs import get_or_create_smiles_vocabs
from transformer.data_funcs import calculate_max_mz
from transformer.transformer_utils import split_and_load_tokenized_multimodal_data
from transformer.data_funcs import bin_spectrum
from transformer.models import MultimodalVITSeq2SeqBeam
from transformer.sequence_pred import train_multimodal_beam_model
from transformer.evaluation import evaluate_multimodal_beam_model, plot_training_history

In [2]:
if torch.cuda.is_available():
    print("CUDA is available.")
    print("PyTorch version:", torch.__version__)
    print("CUDA version:", torch.version.cuda)
    print("Number of available GPUs:", torch.cuda.device_count())
    print("GPU name:", torch.cuda.get_device_name(0))
else:
    print("CUDA is not available.")

CUDA is available.
PyTorch version: 2.1.0+cu121
CUDA version: 12.1
Number of available GPUs: 1
GPU name: NVIDIA GeForce RTX 4060 Laptop GPU

In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda

In [4]:
ir = pd.read_feather('data/ir_spectra_v2.feather')
ir.columns= ['SMILES', 'spectrum']

In [5]:
ir.head()

,SMILES,spectrum
0,COc1nc2ccccc2cc1C(=O)O,"[-0.004481, 0.007279, -0.006439, 0.007464, -0...."
1,CCOC(=O)c1cc2c(OCc3coc4cc(F)ccc34)cccc2n1C(=O)...,"[0.028195, 0.011433, 0.024865, -0.00816, 0.055..."
2,CCCCOc1c(CN2C(=O)c3ccccc3C2=O)n(CC2CC2)c(=O)c2...,"[-0.003043, 0.014693, -0.003067, 0.025262, -0...."
3,CCCCNC[C@@H]1O[C@](O)(CO)[C@@H](O)[C@@H]1O,"[0.099321, 0.155452, 0.048156, 0.19118, 0.0237..."
4,O=C(NCC1CC1)c1nc2c(N3CCC(n4c(=O)[nH]c5ccccc54)...,"[0.2335, 0.090925, 0.061724, 0.158822, 0.04248..."

In [6]:
ms = pd.read_feather('data/msms_cfmid_positive_40ev_v2.feather')
ms.columns = ['SMILES', 'spectrum']

In [7]:
ms.head()

,SMILES,spectrum
0,COc1nc2ccccc2cc1C(=O)O,"[[101.03858, 100.0], [103.05423, 43.72], [104...."
1,CCOC(=O)c1cc2c(OCc3coc4cc(F)ccc34)cccc2n1C(=O)...,"[[57.06988, 51.14], [91.05423, 9.59], [121.044..."
2,CCCCOc1c(CN2C(=O)c3ccccc3C2=O)n(CC2CC2)c(=O)c2...,"[[57.06988, 28.12], [105.03349, 100.0], [117.0..."
3,CCCCNC[C@@H]1O[C@](O)(CO)[C@@H](O)[C@@H]1O,"[[30.03383, 36.99], [41.03858, 8.43], [42.0338..."
4,O=C(NCC1CC1)c1nc2c(N3CCC(n4c(=O)[nH]c5ccccc54)...,"[[55.05423, 63.08], [70.02874, 18.67], [70.065..."

In [8]:
# Minimal test
n = 50000
df_ir = ir.sample(n, random_state=42)
df_ir_test = ir.drop(index=df_ir.index).sample(n//2, random_state=42)
df_ms = ms.loc[df_ir.index]
df_ms_test = ms.loc[df_ir_test.index]

In [9]:
df_ir.reset_index(drop=True, inplace=True)
df_ir_test.reset_index(drop=True, inplace=True)
df_ms.reset_index(drop=True, inplace=True)
df_ms_test.reset_index(drop=True, inplace=True)

In [10]:
method='direct'

In [11]:
smiles_vocabs = get_or_create_smiles_vocabs(pd.concat([ms, ir]), smiles_col='SMILES', source='msd')

Loading existing character vocabulary...
SMILES vocabulary size (character): 39
Loading existing atom_wise vocabulary...
SMILES vocabulary size (atom_wise): 14
Loading existing substructure vocabulary...
SMILES vocabulary size (substructure): 3767143

In [12]:
max_mz = calculate_max_mz(pd.concat([ms]), spectrum_column='spectrum', dtype=np.array)

In [13]:
max_ir = ir['spectrum'].apply(lambda x: len(x)).max()

In [14]:
max_smiles = pd.concat([ms, ir])['SMILES'].apply(lambda x: len(x)).max()

In [15]:
max_smiles

127

In [16]:
pd.concat([ms, ir]).loc[pd.concat([ms, ir])['SMILES'].apply(lambda x: len(x)) > 1000]

Empty DataFrame
Columns: [SMILES, spectrum]
Index: []

In [17]:
train_data = {
    'MS': df_ms,
    'IR': df_ir
}
test_data = {
    'MS': df_ms_test,
    'IR': df_ir_test
}
tokenization_methods = {
    'MS': 'direct',
    'IR': 'direct'
}
max_values = {
    'MS': max_mz,
    'IR': max_ir,
    'SMILES': max_smiles,
}

In [18]:
df_ms['spectrum'] = df_ms['spectrum'].apply(lambda x: bin_spectrum(x, max_mz))
df_ms_test['spectrum'] = df_ms_test['spectrum'].apply(lambda x: bin_spectrum(x, max_mz))

In [19]:
results = {}
for key, value in tokenization_methods.items():
    print(f"\n{key} spectra tokenized with {value} tokenization")
print(f"\nSMILES tokenized with {'character'} tokenization")
smiles_vocab = smiles_vocabs['character']

train_loader, test_loader = split_and_load_tokenized_multimodal_data(
    train_data_dict=train_data,
    train_smiles=df_ms['SMILES'],
    test_data_dict=test_data,
    test_smiles=df_ms_test['SMILES'],
    tokenization_methods=tokenization_methods,
    smiles_vocab=smiles_vocabs['character'],
    max_values=max_values,
)

#num_classes = len(label_encoder.classes_)
smiles_vocab_size = len(smiles_vocab)

# sample batch used for input dimensions
sample_batch, target_batch = next(iter(train_loader))
for key in tokenization_methods.keys():
    print(key, "spectra shape:", sample_batch[key].shape)
print("SMILES shape:", target_batch.shape)
embed_depth = sample_batch['MS'].shape[3]

MS spectra tokenized with direct tokenization

IR spectra tokenized with direct tokenization

SMILES tokenized with character tokenization
MS spectra shape: torch.Size([32, 1, 68, 16])
IR spectra shape: torch.Size([32, 1, 113, 16])
SMILES shape: torch.Size([32, 86])

In [20]:
modality_configs = {
    'MS': {
        'embed_depth': 16,
        'max_length': sample_batch['MS'].shape[2],
    },
    'IR': {
        'embed_depth': 16,
        'max_length': sample_batch['IR'].shape[2],
    }
}

In [21]:
modality_configs

{'MS': {'embed_depth': 16, 'max_length': 68},
 'IR': {'embed_depth': 16, 'max_length': 113}}

In [22]:
model = MultimodalVITSeq2SeqBeam(
    smiles_vocab_size=len(smiles_vocab),
    modality_configs=modality_configs,
    d_model=64,             # 256
    nhead=4,                # 8
    num_layers=2,           # 6
    dim_feedforward=256,    # 2048
)

/home/kyle/anaconda3/envs/ml/lib/python3.11/site-packages/torch/nn/modules/transformer.py:282: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")

In [23]:
model.state_dict()

OrderedDict([('modality_embeddings.MS.weight',
              tensor([[-0.0506, -0.0015, -0.0287,  ..., -0.0772, -0.0841, -0.0076],
                      [-0.0359, -0.0204, -0.0064,  ..., -0.0753, -0.0728,  0.0489],
                      [-0.0758, -0.0204,  0.0512,  ...,  0.0976, -0.0205,  0.0793],
                      ...,
                      [-0.0064,  0.0637, -0.0795,  ...,  0.0187, -0.0054, -0.0039],
                      [-0.0675, -0.0797,  0.0172,  ...,  0.0099,  0.0903, -0.0401],
                      [ 0.0428,  0.0112,  0.0665,  ..., -0.0891, -0.0982,  0.0054]])),
             ('modality_embeddings.MS.bias',
              tensor([-0.0636, -0.1398, -0.1819,  0.0191,  0.1635,  0.1638,  0.1796,  0.0017,
                      -0.1247, -0.2062,  0.1274,  0.0594,  0.1307,  0.1461,  0.0793, -0.0579,
                      -0.0996,  0.0470, -0.1723, -0.0237,  0.0287, -0.1370, -0.2093,  0.1297,
                       0.1350, -0.0257,  0.0571, -0.2240, -0.2020, -0.2096,  0.0229, -0.1487,
                       0.0117,  0.1703, -0.0904,  0.0146, -0.0705, -0.1722,  0.0146,  0.1978,
                       0.1702,  0.1044,  0.2045, -0.1535,  0.1171,  0.1602, -0.1390, -0.0522,
                      -0.1826,  0.1446, -0.2411,  0.2288,  0.0767, -0.1725, -0.2123,  0.1410,
                      -0.1999, -0.0518,  0.0417,  0.2307, -0.2143,  0.1806,  0.1494, -0.2015])),
             ('modality_embeddings.IR.weight',
              tensor([[-0.0074, -0.0020,  0.0230,  ...,  0.0405,  0.0880,  0.0274],
                      [ 0.0599, -0.0480, -0.0582,  ..., -0.0066,  0.0194,  0.0324],
                      [-0.0012, -0.0379,  0.0855,  ..., -0.0213, -0.0572,  0.0897],
                      ...,
                      [ 0.0661, -0.0712,  0.0999,  ..., -0.0754,  0.0713,  0.0697],
                      [-0.0415,  0.0801,  0.0006,  ...,  0.0971, -0.0454, -0.0673],
                      [-0.0454,  0.0980, -0.0769,  ..., -0.0873, -0.0686, -0.0692]])),
             ('modality_embeddings.IR.bias',
              tensor([-0.1130, -0.0087, -0.1363, -0.0445, -0.2211, -0.0680, -0.1738, -0.1549,
                       0.0625,  0.1019, -0.0696,  0.0786, -0.2349,  0.1669,  0.2057, -0.1281,
                      -0.0043,  0.1587,  0.0205,  0.0279,  0.0368, -0.1348,  0.2004,  0.1537,
                      -0.1228, -0.0114,  0.2473,  0.0814,  0.0779,  0.1570,  0.2474, -0.1029,
                      -0.0942,  0.1015, -0.0718,  0.2400, -0.1543, -0.1622, -0.0332,  0.2194,
                       0.0731, -0.2356,  0.0360, -0.0578, -0.0497,  0.1051, -0.1388,  0.2367,
                       0.1782,  0.1338, -0.1076, -0.2074,  0.0114,  0.0174,  0.0599, -0.2128,
                      -0.0308,  0.1781,  0.1805,  0.1832,  0.2403, -0.2324,  0.0031, -0.2159])),
             ('modality_type_embeddings.weight',
              tensor([[ 0.0023,  0.0428,  0.0985,  0.0971, -0.0085,  0.0520, -0.0449,  0.0943,
                       -0.0157, -0.0556, -0.0114, -0.0299, -0.0205, -0.0010,  0.0915,  0.0018,
                       -0.0622, -0.0082,  0.0557,  0.0783,  0.0222, -0.0145, -0.0710,  0.0884,
                       -0.0528,  0.0735, -0.0316, -0.0051, -0.0963,  0.0563, -0.0142,  0.0061,
                        0.0622,  0.0855, -0.0596, -0.0874, -0.0055, -0.0839,  0.0411, -0.0698,
                       -0.0600,  0.0402, -0.0439,  0.0672,  0.0559,  0.0582,  0.0710,  0.0309,
                        0.0932, -0.0885,  0.0646,  0.0054, -0.0742, -0.0508, -0.0506, -0.0357,
                       -0.0881, -0.0542, -0.0544, -0.0751,  0.0092, -0.0075, -0.0410,  0.0394],
                      [-0.0133,  0.0520,  0.0507,  0.0709, -0.0812,  0.0334, -0.0493, -0.0577,
                        0.0330,  0.0551, -0.0889, -0.0916,  0.0998, -0.0834,  0.0972,  0.0442,
                        0.0481,  0.0627, -0.0021, -0.0959,  0.0024,  0.0737, -0.0349, -0.0337,
                        0.0058,  0.0133, -0.0772,  0.0992, -0.0360,  0.0835, -0.0211, -0.0996,
                        0.0981,  0.0289,  0.0003,  0.0685,  0.0957, -0.0878, -0.0685, -0.0207,
                       -0.0990, -0.0809,  0.0160, -0.0325,  0.0236,  0.0524,  0.0562, -0.0967,
                        0.0238, -0.0404, -0.0857, -0.0026, -0.0669, -0.0524, -0.0035, -0.0097,
                        0.0108, -0.0767,  0.0655,  0.0150, -0.0410,  0.0070,  0.0838, -0.0973]])),
             ('pos_encoder.pe',
              tensor([[[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  ...,  1.0000e+00,
                         0.0000e+00,  1.0000e+00]],

                      [[ 8.4147e-01,  5.4030e-01,  6.8156e-01,  ...,  1.0000e+00,
                         1.3335e-04,  1.0000e+00]],

                      [[ 9.0930e-01, -4.1615e-01,  9.9748e-01,  ...,  1.0000e+00,
                         2.6670e-04,  1.0000e+00]],

                      ...,

                      [[ 9.5625e-01, -2.9254e-01,  6.4315e-01,  ...,  6.3049e-01,
                         6.1813e-01,  7.8608e-01]],

                      [[ 2.7050e-01, -9.6272e-01, -5.1133e-02,  ...,  6.3036e-01,
                         6.1823e-01,  7.8599e-01]],

                      [[-6.6395e-01, -7.4778e-01, -7.1816e-01,  ...,  6.3022e-01,
                         6.1834e-01,  7.8591e-01]]])),
             ('length_adapters.MS.weight',
              tensor([[ 0.0376, -0.0581, -0.0785,  ..., -0.0762, -0.0277,  0.0547],
                      [-0.0226, -0.0535,  0.0890,  ...,  0.0045,  0.0894, -0.0236],
                      [ 0.0872, -0.0478, -0.0300,  ..., -0.0209,  0.0184,  0.0106],
                      ...,
                      [-0.0203,  0.0286,  0.0723,  ..., -0.0545,  0.0384, -0.0222],
                      [-0.0431, -0.0410,  0.0602,  ..., -0.0103, -0.0092,  0.0323],
                      [ 0.0010, -0.0794,  0.0957,  ..., -0.0207,  0.0444,  0.0852]])),
             ('length_adapters.MS.bias',
              tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])),
             ('length_adapters.IR.weight',
              tensor([[ 0.0652,  0.0397, -0.0557,  ...,  0.0669,  0.0454,  0.0247],
                      [ 0.0068,  0.0413,  0.0396,  ...,  0.0477,  0.0776, -0.0473],
                      [ 0.0917,  0.0296,  0.0866,  ..., -0.0055,  0.0485, -0.0313],
                      ...,
                      [ 0.0414, -0.0978,  0.0239,  ...,  0.0501, -0.0202, -0.0107],
                      [-0.0589,  0.0626,  0.0780,  ..., -0.0036, -0.0367, -0.0729],
                      [-0.0122,  0.0569, -0.0696,  ...,  0.0188, -0.0192, -0.0223]])),
             ('length_adapters.IR.bias',
              tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])),
             ('transformer_encoder.layers.0.self_attn.in_proj_weight',
              tensor([[-0.0818,  0.0464,  0.1122,  ...,  0.0957,  0.1337, -0.0862],
                      [ 0.1502,  0.1100, -0.0564,  ...,  0.0396, -0.0015,  0.1378],
                      [-0.0607, -0.0703,  0.0134,  ...,  0.0221,  0.0389,  0.1130],
                      ...,
                      [-0.0109, -0.0081, -0.1403,  ..., -0.0153,  0.0944,  0.1284],
                      [ 0.1496, -0.0151, -0.1131,  ..., -0.1495, -0.1263,  0.0638],
                      [ 0.1273, -0.1155, -0.0640,  ..., -0.0545, -0.1328,  0.0742]])),
             ('transformer_encoder.layers.0.self_attn.in_proj_bias',
              tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])),
             ('transformer_encoder.layers.0.self_attn.out_proj.weight',
              tensor([[-0.0777,  0.1196, -0.1023,  ..., -0.0121,  0.1156,  0.0253],
                      [-0.0188, -0.0616, -0.0168,  ...,  0.0628, -0.0809,  0.0708],
                      [ 0.0500, -0.0414,  0.0960,  ..., -0.0866, -0.0763,  0.1193],
                      ...,
                      [-0.1166,  0.0610,  0.0915,  ..., -0.0244, -0.0541, -0.0225],
                      [-0.0692,  0.1125, -0.0718,  ..., -0.0074,  0.0410, -0.1085],
                      [-0.0189, -0.0539, -0.0507,  ..., -0.0843, -0.1214, -0.1221]])),
             ('transformer_encoder.layers.0.self_attn.out_proj.bias',
              tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])),
             ('transformer_encoder.layers.0.linear1.weight',
              tensor([[ 0.0565,  0.1177, -0.0498,  ..., -0.0127, -0.0585, -0.0268],
                      [-0.0249,  0.0195, -0.0111,  ..., -0.0614,  0.0042, -0.0486],
                      [-0.0366, -0.0879, -0.0741,  ..., -0.0386, -0.0164,  0.1056],
                      ...,
                      [ 0.0172, -0.0102,  0.0417,  ..., -0.0926,  0.0903, -0.0573],
                      [-0.0416,  0.0610,  0.0591,  ..., -0.1101, -0.1024,  0.0240],
                      [-0.0556, -0.0126,  0.0242,  ..., -0.0167, -0.0790,  0.1181]])),
             ('transformer_encoder.layers.0.linear1.bias',
              tensor([-0.0058,  0.0712,  0.1237, -0.0800, -0.0993,  0.1135,  0.0569,  0.1035,
                      -0.0095, -0.0317, -0.0486, -0.0457, -0.1159, -0.1229,  0.1144, -0.0041,
                      -0.0647, -0.0570,  0.0331,  0.0580,  0.0150,  0.1191,  0.0966,  0.1132,
                       0.0443, -0.1204,  0.1249, -0.1008, -0.0766,  0.0104,  0.1061,  0.0834,
                      -0.0754,  0.0264, -0.0295, -0.0279,  0.0319,  0.0953, -0.0036,  0.0706,
                       0.0908,  0.0515,  0.0957, -0.1113,  0.1147,  0.1204,  0.0708,  0.0339,
                      -0.0098, -0.1179,  0.0722, -0.0794,  0.1039,  0.0559,  0.0336, -0.0531,
                      -0.0297, -0.0105,  0.0831,  0.0570,  0.0774, -0.0086,  0.0447, -0.0894,
                       0.0887,  0.0739, -0.0880, -0.0854,  0.0453,  0.1165,  0.0700,  0.0958,
                       0.0318, -0.0394,  0.0652,  0.0712, -0.0816, -0.0018, -0.0540,  0.0043,
                       0.0480,  0.0634, -0.1144, -0.1164, -0.0946, -0.0606,  0.0300, -0.0735,
                       0.0708, -0.0911, -0.0929, -0.0349, -0.0244,  0.0930,  0.0678, -0.0577,
                      -0.0401,  0.0663, -0.0528,  0.0015, -0.0054,  0.0368, -0.1249,  0.0481,
                       0.0133, -0.0615,  0.1027,  0.0463, -0.0115,  0.0358,  0.0149, -0.0690,
                      -0.0850,  0.0593,  0.0824, -0.0780,  0.0531, -0.1019,  0.0699, -0.0556,
                       0.0076, -0.0204, -0.0495, -0.1004, -0.0891,  0.0304,  0.0384, -0.0598,
                      -0.1112,  0.0718,  0.0271, -0.0636, -0.0279, -0.0964, -0.0265, -0.0693,
                       0.0635, -0.0473, -0.0249, -0.0283, -0.0151, -0.0751,  0.0307, -0.1099,
                       0.0794, -0.1227,  0.1100, -0.0495, -0.1220, -0.1149, -0.0842,  0.0175,
                       0.0013, -0.0640, -0.1057,  0.0448,  0.0693,  0.1189, -0.0703, -0.0914,
                      -0.0880, -0.1023,  0.0790, -0.0025,  0.0468, -0.0685,  0.1199,  0.0538,
                       0.0722, -0.0194,  0.1063, -0.0129,  0.0572,  0.0831, -0.0554,  0.0251,
                      -0.1068, -0.0842,  0.0517,  0.0892, -0.0261,  0.0470,  0.0293, -0.0870,
                       0.0913, -0.0962, -0.0241, -0.0524, -0.1160, -0.0354, -0.0805, -0.0562,
                      -0.0217,  0.0944,  0.0367,  0.1009, -0.1164, -0.0446,  0.0790,  0.0268,
                      -0.1195,  0.0405, -0.0502, -0.0439,  0.1109, -0.0889,  0.0973, -0.1059,
                       0.1099, -0.0822,  0.1015, -0.0266, -0.1058, -0.0555, -0.1237,  0.0866,
                      -0.0921,  0.0552,  0.0892, -0.0259, -0.0563, -0.0741,  0.1095,  0.1174,
                       0.1138,  0.0857, -0.1086,  0.0322,  0.0456, -0.0881, -0.1221,  0.1135,
                       0.0324,  0.0878, -0.0359,  0.0698, -0.0172,  0.1237, -0.0954,  0.1235,
                       0.0315, -0.0625, -0.0095, -0.0201, -0.0270,  0.0745, -0.0183, -0.0926,
                      -0.0943, -0.0822,  0.0276,  0.0102, -0.0048,  0.0842, -0.1197, -0.0292])),
             ('transformer_encoder.layers.0.linear2.weight',
              tensor([[ 0.0435,  0.0430, -0.0323,  ..., -0.0223,  0.0427, -0.0410],
                      [ 0.0352,  0.0080, -0.0003,  ..., -0.0180,  0.0102, -0.0155],
                      [-0.0295,  0.0584,  0.0600,  ...,  0.0319, -0.0415, -0.0441],
                      ...,
                      [-0.0029,  0.0430,  0.0559,  ...,  0.0589,  0.0102, -0.0052],
                      [ 0.0497,  0.0475,  0.0513,  ...,  0.0230, -0.0020,  0.0029],
                      [-0.0557,  0.0055, -0.0059,  ...,  0.0346, -0.0195,  0.0443]])),
             ('transformer_encoder.layers.0.linear2.bias',
              tensor([-0.0259, -0.0020, -0.0558, -0.0432, -0.0007, -0.0112,  0.0272, -0.0049,
                       0.0133, -0.0389, -0.0225,  0.0085,  0.0349,  0.0249, -0.0498,  0.0487,
                       0.0137,  0.0385,  0.0527,  0.0179, -0.0314,  0.0265,  0.0247,  0.0368,
                       0.0565, -0.0522,  0.0281,  0.0089, -0.0435, -0.0593,  0.0407, -0.0186,
                       0.0048,  0.0371,  0.0159, -0.0340, -0.0487,  0.0570,  0.0537, -0.0606,
                      -0.0155, -0.0326, -0.0404,  0.0346, -0.0027,  0.0266,  0.0605, -0.0402,
                      -0.0042, -0.0303, -0.0468,  0.0029,  0.0134,  0.0138, -0.0049,  0.0528,
                      -0.0272,  0.0248,  0.0462, -0.0505, -0.0437, -0.0399, -0.0123, -0.0313])),
             ('transformer_encoder.layers.0.norm1.weight',
              tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])),
             ('transformer_encoder.layers.0.norm1.bias',
              tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])),
             ('transformer_encoder.layers.0.norm2.weight',
              tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])),
             ('transformer_encoder.layers.0.norm2.bias',
              tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])),
             ('transformer_encoder.layers.1.self_attn.in_proj_weight',
              tensor([[-0.0818,  0.0464,  0.1122,  ...,  0.0957,  0.1337, -0.0862],
                      [ 0.1502,  0.1100, -0.0564,  ...,  0.0396, -0.0015,  0.1378],
                      [-0.0607, -0.0703,  0.0134,  ...,  0.0221,  0.0389,  0.1130],
                      ...,
                      [-0.0109, -0.0081, -0.1403,  ..., -0.0153,  0.0944,  0.1284],
                      [ 0.1496, -0.0151, -0.1131,  ..., -0.1495, -0.1263,  0.0638],
                      [ 0.1273, -0.1155, -0.0640,  ..., -0.0545, -0.1328,  0.0742]])),
             ('transformer_encoder.layers.1.self_attn.in_proj_bias',
              tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])),
             ('transformer_encoder.layers.1.self_attn.out_proj.weight',
              tensor([[-0.0777,  0.1196, -0.1023,  ..., -0.0121,  0.1156,  0.0253],
                      [-0.0188, -0.0616, -0.0168,  ...,  0.0628, -0.0809,  0.0708],
                      [ 0.0500, -0.0414,  0.0960,  ..., -0.0866, -0.0763,  0.1193],
                      ...,
                      [-0.1166,  0.0610,  0.0915,  ..., -0.0244, -0.0541, -0.0225],
                      [-0.0692,  0.1125, -0.0718,  ..., -0.0074,  0.0410, -0.1085],
                      [-0.0189, -0.0539, -0.0507,  ..., -0.0843, -0.1214, -0.1221]])),
             ('transformer_encoder.layers.1.self_attn.out_proj.bias',
              tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])),
             ('transformer_encoder.layers.1.linear1.weight',
              tensor([[ 0.0565,  0.1177, -0.0498,  ..., -0.0127, -0.0585, -0.0268],
                      [-0.0249,  0.0195, -0.0111,  ..., -0.0614,  0.0042, -0.0486],
                      [-0.0366, -0.0879, -0.0741,  ..., -0.0386, -0.0164,  0.1056],
                      ...,
                      [ 0.0172, -0.0102,  0.0417,  ..., -0.0926,  0.0903, -0.0573],
                      [-0.0416,  0.0610,  0.0591,  ..., -0.1101, -0.1024,  0.0240],
                      [-0.0556, -0.0126,  0.0242,  ..., -0.0167, -0.0790,  0.1181]])),
             ('transformer_encoder.layers.1.linear1.bias',
              tensor([-0.0058,  0.0712,  0.1237, -0.0800, -0.0993,  0.1135,  0.0569,  0.1035,
                      -0.0095, -0.0317, -0.0486, -0.0457, -0.1159, -0.1229,  0.1144, -0.0041,
                      -0.0647, -0.0570,  0.0331,  0.0580,  0.0150,  0.1191,  0.0966,  0.1132,

In [24]:
optimizer = optim.Adam(model.parameters(), lr=0.0001)
criterion = nn.CrossEntropyLoss()#ignore_index=smiles_vocab['<pad>'])

model, history = train_multimodal_beam_model(
    model=model,
    train_loader=train_loader,
    test_loader=test_loader,
    optimizer=optimizer,
    criterion=criterion,
    num_epochs=1,
    evaluate=False,
    verbose=2,
    checkpoint_path='model_checkpoints/',
    use_tensorboard=True,
)

TensorBoard logs will be saved to runs/20250123-093059
Saving checkpoints to model_checkpoints/checkpoint_3

Epoch 1/1 [Train]:   0%|          | 0/1563 [00:00<?, ?it/s]

In [21]:
results = evaluate_multimodal_beam_model(
    model=model, 
    test_loader=test_loader, 
    smiles_vocab=smiles_vocab, 
    beam_width=5,
    verbose=1
)

Evaluating:   0%|          | 0/782 [00:00<?, ?it/s]

AttributeError: 'dict' object has no attribute 'size'

In [ ]:
plot_training_history(history)

In [ ]:
results

In [ ]:
history